<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="UserDetails.aspx.cs" Inherits="Asp_DotNet_Project.UserDetails" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

    <style>
        .modern-grid {
            width: 100%;
            background-color: #fff;
            margin: 16px 0 24px 0;
            border: 1px solid #525252;
            border-collapse: collapse;
            font-family: 'Segoe UI', Arial, sans-serif;
            font-size: 1em;
            box-shadow: 0 2px 6px rgba(0,0,0,0.07);
        }

            .modern-grid th {
                padding: 12px 8px;
                background: linear-gradient(90deg, #615fcf 0%, #7379e6 100%);
                color: #fff;
                border-left: 1px solid #525252;
                border-bottom: 2px solid #3938b6;
                font-size: 1.06em;
                text-align: left;
            }

            .modern-grid tr {
                transition: background 0.23s;
            }

            .modern-grid td {
                padding: 11px 8px;
                border: 1px solid #c1c1c1;
                color: #434343;
                background: #fafbfc;
            }

            .modern-grid tr:nth-child(even) td {
                background: #f1f4ff;
            }

            .modern-grid tr:hover td {
                background: #e9edfa;
            }

            .modern-grid .GridViewPager,
            .modern-grid .aspNetPager {
                background: #615fcf;
                text-align: right;
                padding: 5px 12px;
            }

                .modern-grid .GridViewPager a,
                .modern-grid .aspNetPager a {
                    color: #fff;
                    margin: 0 3px;
                    padding: 5px 9px;
                    border-radius: 5px;
                    text-decoration: none;
                    background: #7379e6;
                }

                    .modern-grid .GridViewPager a:hover,
                    .modern-grid .aspNetPager a:hover {
                        background: #3938b6;
                    }

        .gridTextbox {
            width: 95%;
            box-sizing: border-box;
            padding: 4px;
            font-size: 14px;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div>
        <h2 class="h2">User Details</h2>
        <asp:GridView ID="GridView1" runat="server" DataKeyNames="Id" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="modern-grid" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowCancelingEdit="GridView1_RowCancelingEdit">
            <Columns>
                <asp:TemplateField HeaderText="Sr.No">
                    <ItemTemplate>
                        <%# Container.DataItemIndex + 1 %>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="ID">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox" runat="server" Text='<%# Bind("Id") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="First Name">
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Firstname") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtFirstname" CssClass="gridTextbox" runat="server" Text='<%# Bind("Firstname") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Last Name">
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Lastname") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtLastName" CssClass="gridTextbox" runat="server" Text='<%# Bind("Lastname") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Email">
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtEmail" CssClass="gridTextbox" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Phone">
                    <ItemTemplate>
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("Phone") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtPhone" CssClass="gridTextbox" runat="server" Text='<%# Bind("Phone") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Address">
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Address") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtAddress" CssClass="gridTextbox" runat="server" Text='<%# Bind("Address") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>

    </div>
</asp:Content>
