<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="ManageUser.aspx.cs" Inherits="Asp_DotNet_Project.Admin.ManageUser" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        .modern-grid {
            width: 100%;
            background-color: #fff;
            margin: 16px 0 24px 0;
            border: 1px solid #525252;
            border-collapse: collapse;
            font-family: 'Segoe UI', Arial, sans-serif;
            font-size: 1em;
            box-shadow: 0 2px 6px rgba(0,0,0,0.07);
        }

            .modern-grid th {
                padding: 12px 8px;
                background: linear-gradient(90deg, #615fcf 0%, #7379e6 100%);
                color: #fff;
                border-left: 1px solid #525252;
                border-bottom: 2px solid #3938b6;
                font-size: 1.06em;
                text-align: left;
            }

            .modern-grid tr {
                transition: background 0.23s;
            }

            .modern-grid td {
                padding: 11px 8px;
                border: 1px solid #c1c1c1;
                color: #434343;
                background: #fafbfc;
            }

            .modern-grid tr:nth-child(even) td {
                background: #f1f4ff;
            }

            .modern-grid tr:hover td {
                background: #e9edfa;
            }

            .modern-grid .GridViewPager,
            .modern-grid .aspNetPager {
                background: #615fcf;
                text-align: right;
                padding: 5px 12px;
            }

                .modern-grid .GridViewPager a,
                .modern-grid .aspNetPager a {
                    color: #fff;
                    margin: 0 3px;
                    padding: 5px 9px;
                    border-radius: 5px;
                    text-decoration: none;
                    background: #7379e6;
                }

                    .modern-grid .GridViewPager a:hover,
                    .modern-grid .aspNetPager a:hover {
                        background: #3938b6;
                    }

        .gridTextbox {
            width: 95%;
            box-sizing: border-box;
            padding: 4px;
            font-size: 14px;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container mt-4">
        <div class="card shadow-lg border-0">
            <div class="card-header  text-center fs-4 fw-bold">
                User Details
            </div>
            <div class="card-body p-0">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                    DataKeyNames="Id" OnRowEditing="GridView1_RowEditing"
                    OnRowCancelingEdit="GridView1_RowCancelingEdit"
                    OnRowUpdating="GridView1_RowUpdating"
                    AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowPaging="true" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowDeleting="GridView1_RowDeleting" CssClass="table table-bordered table-hover table-striped mb-0 align-middle text-center"
                    HeaderStyle-CssClass="table-primary"
                    RowStyle-CssClass="align-middle"
                    AlternatingRowStyle-CssClass="table-light"
                    GridLines="None">
                    <Columns>

                        <asp:TemplateField HeaderText="Sr.No">
                            <ItemTemplate>
                                <%# Container.DataItemIndex + 1 %>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="First Name">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtFirstname" runat="server" CssClass="form-control"
                                    Text='<%# Bind("Firstname") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" CssClass="fw-bold"
                                    Text='<%# Bind("Firstname") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Last Name">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtLastName" runat="server" CssClass="form-control"
                                    Text='<%# Bind("Lastname") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label3" runat="server" CssClass="fw-bold text-dark"
                                    Text='<%# Bind("Lastname") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Email">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEmail" runat="server" CssClass="form-control"
                                    Text='<%# Bind("Email") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label4" runat="server" CssClass="text-muted"
                                    Text='<%# Bind("Email") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Phone">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtPhone" runat="server" CssClass="form-control"
                                    Text='<%# Bind("Phone") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label5" runat="server" CssClass="text-success"
                                    Text='<%# Bind("Phone") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Address">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtAddress" runat="server" CssClass="form-control"
                                    Text='<%# Bind("Address") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label6" runat="server" CssClass="text-secondary"
                                    Text='<%# Bind("Address") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                    <RowStyle ForeColor="#000066" />
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#007DBB" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#00547E" />


                </asp:GridView>
            </div>
        </div>
    </div>

</asp:Content>
